### ISSUE TITLE
hubverse-transform: add a temporary patch for schema mismatch errors

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/hubverse-transform#24]
**Background**

We plan to add a feature to hubverse-transform that will enable the use of hub-specific schemas when converting incoming model-output files to parquet: https://github.com/hubverse-org/hubverse-transform/issues/14

Progress on that feature, however, has taken a backseat to the work we're doing on Hubverse visualizations.

In the meantime, hubs that have been onboarded to the cloud (specifically last season's CDC FluSight) are paying a performance penalty due to workarounds in place to accommodate non-uniform model-output file schemas.

This issue proposes to add a temporary patch to hubverse-transform that will force our two most "problematic" model-output fields to character.

**Definition of done**

- [ ] parquet schema for S3 model-output files forces `location` to character
- [ ] parquet schema for S3 model-output files forces `output_type_id` to character

**Comment by bsweger** [comment]
@matthewcornell and I have been pairing on this and have some working code in this branch: https://github.com/hubverse-org/hubverse-transform/tree/schema_patch

**Comment by annakrystalli** [comment]
One thing I'm not sure about with this temp fix is the fact that the schema is being applied after reading in: 
https://github.com/hubverse-org/hubverse-transform/blob/5bedb1f90f33001c37664265959e58a5e0202b5f/src/hubverse_transform/model_output.py#L205-L218

I believe this can [cause problems with values like `01`](https://github.com/hubverse-org/hubverse-transform/issues/14#issuecomment-2126612247) as it will transform them to integer on read, dropping the leading zero, and then write them out as `"1"`. I can't see this being explicitly tested for, I can only see output column data type being is checked but not whether the values have been altered in any way. But maybe I'm missing sth as I'm not a python expert.

**Comment by bsweger** [comment]
> One thing I'm not sure about with this temp fix is the fact that the schema is being applied after reading in:
> 
> https://github.com/hubverse-org/hubverse-transform/blob/5bedb1f90f33001c37664265959e58a5e0202b5f/src/hubverse_transform/model_output.py#L205-L218
> 
> I believe this can [cause problems with values like `01`](https://github.com/hubverse-org/hubverse-transform/issues/14#issuecomment-2126612247) as it will transform them to integer on read, dropping the leading zero, and then write them out as `"1"`. I can't see this being explicitly tested for, I can only see output column data type being checked but not whether the values have been altered in any way. But maybe I'm missing sth as I'm not a python expert.

Yeah, we couldn't find a way to apply the schema when reading in w/o knowing the column names in advance (which, of course, we will once we do the work in #14).

So we had to update the schema after the data is read. That is a good point about the zeroes...we haven't finished writing all of the tests yet, but @matthewcornell let's make sure we think this through!
