### ISSUE TITLE
Cloud syncing for variant-nowcast-hub model outputs silently stops after reading model output files

### ISSUE THREAD

**Issue by bsweger** [hubverse-org/hubverse-transform#32]
**Background**

From the related Slack message:

> The AWS lambda that syncs data to S3 silently stops the sync process for the UGA and UMass submissions. These look to be larger (presumably they contain samples?), though not huge.

* The CloudWatch logs emitted by the lambda shows that we're receiving the S3 trigger and starting the transform process. However, the last log we're receiving is a "starting model output file read" message.
* ~~There are no "out of memory" errors in the logs~~
* There are no lambda timeout errors in the logs

**Comment by bsweger** [comment]
There are, in fact, out of memory messages in the logs (that didn't show up on my dashboard, hence, I missed them).

For example:  
```
REPORT RequestId: 976a2f76-a491-49fc-a34f-cf4b4ee3eea5	Duration: 11233.79 ms	Billed Duration: 11234 ms	Memory Size: 128 MB	Max Memory Used: 126 MB	Init Duration: 1338.29 ms	Status: error	Error Type: Runtime.OutOfMemory
```

That provides a concrete problem to solve. For now, I'm inclined to increase the memory, ephemeral storage, and timeout of the transform lambda. A longer term and more robust solution would be to process model_output files in batches to ensure we can handle larger-than-memory data.

**Comment by nickreich** [comment]
I'm going to close this based on [Increase memory and timeout configuration for the transform lambda hubverse-org/hubverse-infrastructure#64](https://github.com/hubverse-org/hubverse-infrastructure/pull/64), but can reopen in the future to address longer-term solution proposed above.
